services:
  - type: web
    plan: free
    runtime: image
    name: n8n-dok7
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Configuración para base de datos externa en AWS
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: dok7
      - key: DB_POSTGRESDB_HOST
        value: dok7-instance.c52446se82ht.eu-west-3.rds.amazonaws.com
      - key: DB_POSTGRESDB_PASSWORD
        value: Phimister-2025!
      - key: DB_POSTGRESDB_USER
        value: postgres